[{"user_id": 275, "stars": [], "topic_id": 43188, "date_created": 1312321370.861469, "message": "I'm trying to build a package for my Django app Copyblock (https://github.com/sivy/django-copyblock) such that the package can live at http://pypi.python.org/pypi/django-copyblock but after installing, can be imported as \"copyblock\".", "group_id": 81, "id": 1779528}, {"user_id": 275, "stars": [], "topic_id": 43188, "date_created": 1312321406.4593749, "message": "my setup.py file is at https://github.com/sivy/django-copyblock/blob/master/setup.py", "group_id": 81, "id": 1779530}, {"user_id": 275, "stars": [], "topic_id": 43188, "date_created": 1312321442.4019179, "message": "i can install via \"pip install django-copyblock\", but running \"import copyblock\" from the shell doesn't find the module.", "group_id": 81, "id": 1779532}, {"user_id": 1822, "stars": [], "topic_id": 43188, "date_created": 1312330580.024539, "message": "You also don't need an __init__ file in your distribution folder, that could just throw off the find_packages util", "group_id": 81, "id": 1780449}, {"user_id": 1822, "stars": [], "topic_id": 43188, "date_created": 1312330550.734035, "message": "a couple things - the name in your setup.py should just be copyblock - that is the module name - your distribution folder has the name django-copyblock", "group_id": 81, "id": 1780445}, {"user_id": 275, "stars": [], "topic_id": 43188, "date_created": 1312418403.9124579, "message": "nice call on the extra __init__", "group_id": 81, "id": 1789754}, {"user_id": 275, "stars": [], "topic_id": 43188, "date_created": 1312418486.850456, "message": "removed", "group_id": 81, "id": 1789761}]