[{"user_id": 25697, "stars": [], "topic_id": 15559, "date_created": 1301200212.467824, "message": "I've spent some time reading command.py and can't really see what it's trying to do.", "group_id": 6812, "id": 449379}, {"user_id": 25697, "stars": [], "topic_id": 15559, "date_created": 1301199951.0235989, "message": "So how do I actually run the program?", "group_id": 6812, "id": 449370}, {"user_id": 25697, "stars": [], "topic_id": 15559, "date_created": 1301200019.095777, "message": "I've set up the example and the commands give me one of two errors:", "group_id": 6812, "id": 449371}, {"user_id": 25697, "stars": [], "topic_id": 15559, "date_created": 1301200073.5735509, "message": "# kokki config.yaml web\nTraceback (most recent call last):\n  File \"/usr/local/bin/kokki\", line 6, in <module>\n    main()\n  File \"/usr/local/lib/python2.6/dist-packages/kokki/command.py\", line 62, in main\n    with open(fname, \"rb\") as fp:\nIOError: [Errno 2] No such file or directory: 'kitchen.py'\n", "group_id": 6812, "id": 449374}, {"user_id": 25697, "stars": [], "topic_id": 15559, "date_created": 1301200085.8347721, "message": "or", "group_id": 6812, "id": 449375}, {"user_id": 25697, "stars": [], "topic_id": 15559, "date_created": 1301200158.7772119, "message": "# kokki -f ~/src/kokki/tests/ test\nFunction for role 'test' not found in config\n", "group_id": 6812, "id": 449377}]