[{"user_id": 9650, "stars": [], "topic_id": 36885, "date_created": 1306411746.5661061, "message": "It occured in our Web server, however, if I pass a unicode string with non-ASCII to os.path, I never get an error. How can I debug this? Apparently, os.path seems to be implemented in C.", "group_id": 292, "id": 1191237}, {"user_id": 9650, "stars": [], "topic_id": 36885, "date_created": 1306411644.6454549, "message": "How can this happen: http://pastebin.com/FCW06ZVm", "group_id": 292, "id": 1191230}, {"user_id": 16551, "stars": [], "topic_id": 36885, "date_created": 1306412648.2023549, "message": "Add something like:\n---------------------------------------------------\nexport LANG='en_US.UTF-8'\nexport LC_ALL='en_US.UTF-8'\n---------------------------------------------------\nto /etc/apache2/envvars or other Apache start up file.", "group_id": 292, "id": 1191317}, {"user_id": 16551, "stars": [], "topic_id": 36885, "date_created": 1306413679.100826, "message": "Are you running concurrent apps in same Apache server, ie., PHP, or other Django applications, that change the language on the fly. Because it is process wide, applications can interfere with each other.", "group_id": 292, "id": 1191399}, {"user_id": 16551, "stars": [], "topic_id": 36885, "date_created": 1306413703.4375429, "message": "If using mod_wsgi, use daemon mode so your application isn't affected by other applications running in the same process.", "group_id": 292, "id": 1191400}, {"user_id": 9650, "stars": [], "topic_id": 36885, "date_created": 1306413781.9588971, "message": "I have Trac and one Django project on the same server.  The Django code throws this error.", "group_id": 292, "id": 1191408}, {"user_id": 16551, "stars": [], "topic_id": 36885, "date_created": 1306412669.7899041, "message": "Some systems default to ASCII for LANG for Apache rather than UTF-8.", "group_id": 292, "id": 1191320}, {"user_id": 9650, "stars": [], "topic_id": 36885, "date_created": 1306413978.526602, "message": "We use WGSI for Trac and Django but probably not in daemon mode.  I'll look into this, thank you!", "group_id": 292, "id": 1191429}, {"user_id": 9650, "stars": [], "topic_id": 36885, "date_created": 1306413524.4246521, "message": "I have already LANG=\"de_DE.UTF-8\" in /etc/default/locale, which is loaded in envvars.  Additionally, it seems to happen only sometimes.  Maybe only one of the Apache processes hadn't loaded /etc/default/locale due to some weird error?", "group_id": 292, "id": 1191389}, {"user_id": 16551, "stars": [], "topic_id": 36885, "date_created": 1306413728.3411019, "message": "See http://code.google.com/p/modwsgi/wiki/ApplicationIssues#Timezone_and_Locale_Settings", "group_id": 292, "id": 1191405}, {"user_id": 34413, "stars": [], "topic_id": 36885, "date_created": 1306480018.035996, "message": "Django is so bad", "group_id": 292, "id": 1201712}, {"user_id": 34413, "stars": [], "topic_id": 36885, "date_created": 1306479990.839318, "message": "nono", "group_id": 292, "id": 1201708}]