[{"user_id": 10074, "stars": [], "topic_id": 14661, "date_created": 1300871646.291486, "message": "Hey guys :)\nI try to import a dynamic located .py file. In plugins/<name>/config.py (<name> is the name of a plugin) I have a dictionary called config_dic = {..}. Now I want to use this dictionary and I tried this: my_config = __import__(\"plugins.\"+plugin+\".config\").config_dic but this does not work (No module named plugins.default.config)", "group_id": 292, "id": 415563}, {"user_id": 10074, "stars": [{"date_created": 1300918595.047112, "user_id": 141}], "topic_id": 14661, "date_created": 1300875036.9329619, "message": "self solved... I had to place __init__.py files in each subfolder. Didn't know that python need those to recognize a folder as a package :)", "group_id": 292, "id": 415822}, {"user_id": 257, "stars": [{"date_created": 1300888221.6687019, "user_id": 22109}, {"date_created": 1300900408.301348, "user_id": 1736}, {"date_created": 1300910794.174346, "user_id": 19652}], "topic_id": 14661, "date_created": 1300882964.0232761, "message": "use importlib.import_module instead of __import__", "group_id": 292, "id": 416594}, {"user_id": 257, "stars": [], "topic_id": 14661, "date_created": 1300882972.673908, "message": "it's also available as a backport for older versions", "group_id": 292, "id": 416596}]