[{"user_id": 7, "stars": [], "topic_id": 14009, "date_created": 1300579413.9684949, "message": "Try running your app with postgresql locally, it won't work there either, this isn't an ep.io issue", "group_id": 2873, "id": 389920}, {"user_id": 21209, "stars": [], "topic_id": 14009, "date_created": 1300578250.406816, "message": "I get this error when I make this query: FollowedTopic.objects.get_or_create(follower=request.user, topic__pk=topic_id, language=language)", "group_id": 2873, "id": 389869}, {"user_id": 21209, "stars": [], "topic_id": 14009, "date_created": 1300578269.680687, "message": "and I don't know why, in local it works (with sqlite3)", "group_id": 2873, "id": 389871}, {"user_id": 8740, "stars": [], "topic_id": 14009, "date_created": 1300580822.7789991, "message": "@patrick91 Alex has a good suggestion; the problem is probably in the configuration. However, if you tell me the app name, I'll fish around in the database logs to see if we can get the main erroring statement out.", "group_id": 2873, "id": 389987}, {"user_id": 21209, "stars": [], "topic_id": 14009, "date_created": 1300626523.0925241, "message": "the app's name is univatma, however I'm trying to install postgresql locally to see if it works here :)", "group_id": 2873, "id": 391877}, {"user_id": 21209, "stars": [], "topic_id": 14009, "date_created": 1300638207.264251, "message": "I can't get postgresql and psycopg2 installed on my mac :(\nhowever the error seems to be caused from an error in sql ( http://stackoverflow.com/questions/1867407/django-templatesyntaxerror-current-transaction-is-aborted-what-does-this-except ) but I don't know how to inspect this :(", "group_id": 2873, "id": 392474}, {"user_id": 8740, "stars": [], "topic_id": 14009, "date_created": 1300638574.0940981, "message": "@patrick91 The postgres cluster says this:", "group_id": 2873, "id": 392506}, {"user_id": 8740, "stars": [], "topic_id": 14009, "date_created": 1300638575.9170201, "message": "2011-03-20 15:17:55 UTC app_8113 app_8113 ERROR:  null value in column \"topic_id\" violates not-null constraint\n2011-03-20 15:17:55 UTC app_8113 app_8113 ERROR:  current transaction is aborted, commands ignored until end of transaction block", "group_id": 2873, "id": 392507}, {"user_id": 21209, "stars": [], "topic_id": 14009, "date_created": 1300640627.076436, "message": "@andrewgodwin I've resolved, it was an error in my code :( Thank you very much for the support :D", "group_id": 2873, "id": 392711}, {"user_id": 8740, "stars": [{"date_created": 1300642653.813324, "user_id": 21209}], "topic_id": 14009, "date_created": 1300642131.912555, "message": "@patrick91 No problem. Hopefully we can get postgres errors appearing on the program's console at some point, they're really helpful in these cases.", "group_id": 2873, "id": 392870}]