[{"user_id": 38112, "stars": [], "topic_id": 43604, "date_created": 1313038606.15411, "message": "Before I did my first upload to epio, I cleared out my migrations because I figured it was going to create a new db anyway. Stupid I know, and now I can't migrate. Is there a way to run the initial migration through epio?", "group_id": 2873, "id": 1845745}, {"user_id": 38112, "stars": [], "topic_id": 43604, "date_created": 1313045679.570977, "message": "Also, is there a way to reverse a migration on epio?", "group_id": 2873, "id": 1846210}, {"user_id": 8740, "stars": [], "topic_id": 43604, "date_created": 1313054007.0226009, "message": "epio django does exactly the same job as ./manage.py would", "group_id": 2873, "id": 1846639}, {"user_id": 8740, "stars": [], "topic_id": 43604, "date_created": 1313053992.856499, "message": "Have you tried the \"epio django\" command? i.e. \"epio django migrate\" to apply all migrations, \"epio django migrate myapp 0001\" to reverse migration 0002", "group_id": 2873, "id": 1846636}, {"user_id": 38112, "stars": [], "topic_id": 43604, "date_created": 1313087640.919512, "message": "But can I run epio django schemamigration --initial myapp", "group_id": 2873, "id": 1850258}, {"user_id": 38112, "stars": [], "topic_id": 43604, "date_created": 1313087699.9001479, "message": "My migrations locally don't match what's on epio. Is there a way to go back from 0001 to the original unmigrated db?", "group_id": 2873, "id": 1850265}, {"user_id": 38112, "stars": [], "topic_id": 43604, "date_created": 1313109533.1364801, "message": "I deleted my app but the db stays? How do I clear my Postgres service?", "group_id": 2873, "id": 1852775}, {"user_id": 8740, "stars": [], "topic_id": 43604, "date_created": 1313161339.0438011, "message": "You can't run schemamigration on ep.io, as that creates migration files - you should be making the migrations on your local machine, committing them into your version control system, and then uploading them and running migrate", "group_id": 2873, "id": 1857638}, {"user_id": 8740, "stars": [{"date_created": 1313972643.9942861, "user_id": 12716}], "topic_id": 43604, "date_created": 1313161373.0888259, "message": "I think you emailed about the database reset, as well - currently, you have to delete your app and make a new one, but we're working on a proper reset.", "group_id": 2873, "id": 1857641}, {"user_id": 32271, "stars": [], "topic_id": 43604, "date_created": 1316762782.4796491, "message": "Hi Andrew, I am trying to run \"epio django migrate website --fake\" but it tells me that", "group_id": 2873, "id": 2195055}, {"user_id": 32271, "stars": [], "topic_id": 43604, "date_created": 1316762834.8749149, "message": "this is the error message: \"no such option: --fake\"", "group_id": 2873, "id": 2195059}, {"user_id": 40383, "stars": [], "topic_id": 43604, "date_created": 1316764642.2156479, "message": "I think epio sees '--' as an arg option passing token.  I wanted to pass --noinput to rebuild_index and -- --noinput worked.  So try: epio django migrate website -- --fake.  It should work.", "group_id": 2873, "id": 2195122}, {"user_id": 32271, "stars": [], "topic_id": 43604, "date_created": 1316764718.3822701, "message": "great. that worked :-) thank you.", "group_id": 2873, "id": 2195125}, {"user_id": 40383, "stars": [], "topic_id": 43604, "date_created": 1316764959.3462529, "message": "welcome ;)  Btw, Andrew, yes, please let us know when proper db reset is ready.", "group_id": 2873, "id": 2195136}, {"user_id": 8740, "stars": [], "topic_id": 43604, "date_created": 1316804987.1403279, "message": "@johnnykl We're still working on it; it's tied up as part of a bigger set of changes", "group_id": 2873, "id": 2198612}, {"user_id": 40383, "stars": [], "topic_id": 43604, "date_created": 1316843988.8426061, "message": "cool ;)", "group_id": 2873, "id": 2201822}]