[{"user_id": 1930, "stars": [], "topic_id": 18681, "date_created": 1302553284.851371, "message": "With virtualenv 1.6 recently released & supporting python3,  I haven't figured out how to get a python3 (3.2) virtual environment up in a context of a default python2.6 environment.  Discussion on how / best practices appreciated!", "group_id": 1535, "id": 629203}, {"user_id": 1930, "stars": [], "topic_id": 18681, "date_created": 1302620264.9321079, "message": "If you've used the new virtualenv (w/ or w/o wrapper) on python 3, I'd like to hear about it.  Thanks.", "group_id": 1535, "id": 643609}, {"user_id": 1963, "stars": [], "topic_id": 18681, "date_created": 1302630330.2348249, "message": "I have yet to get that to work. Interested in hearing how it's done.", "group_id": 1535, "id": 646469}, {"user_id": 1760, "stars": [], "topic_id": 18681, "date_created": 1302696107.1837821, "message": "Don't you just need to install virtualenv under Python 3 and then run the right version when creating your new environment?", "group_id": 1535, "id": 663545}, {"user_id": 1930, "stars": [], "topic_id": 18681, "date_created": 1302716851.9354391, "message": "It looks like my python3 distribute and pip are in site-packages (python3 installed per Ray H.'s instructions for his pycon classes)", "group_id": 1535, "id": 668378}, {"user_id": 1930, "stars": [], "topic_id": 18681, "date_created": 1302717427.045054, "message": "btw, running:   python3 $(which virtualenv) --distribute ENV;  source ENV/bin/activate;    <= seems to work.", "group_id": 1535, "id": 668518}, {"user_id": 1930, "stars": [], "topic_id": 18681, "date_created": 1302716944.7393651, "message": "and get: Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nImportError: No module named virtualenvwrapper.hook_loader\nvirtualenvwrapper.sh: There was a problem running the initialization hooks. If Python could not import the module virtualenvwrapper.hook_loader, check that virtualenv has been installed for VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3 and that PATH is set properly.", "group_id": 1535, "id": 668398}, {"user_id": 1930, "stars": [], "topic_id": 18681, "date_created": 1302716179.6126471, "message": "ok - a little thinking / working out loud:  os-x snow-leopard:  virtualenv 1.6 installed from zip file by python3 (no \"virtualenv3\"  link - just in site-packages)", "group_id": 1535, "id": 668237}, {"user_id": 1930, "stars": [], "topic_id": 18681, "date_created": 1302716880.6100791, "message": "next, I try:   export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3", "group_id": 1535, "id": 668384}, {"user_id": 1930, "stars": [], "topic_id": 18681, "date_created": 1302716219.6076319, "message": "python3 $(which virtualenv)  will run the python3 site-package's  virtualenv....  so far, so good.", "group_id": 1535, "id": 668246}, {"user_id": 1930, "stars": [], "topic_id": 18681, "date_created": 1302716903.4447179, "message": "followed by:  source  /usr/local/bin/virtualevnwrapper.sh", "group_id": 1535, "id": 668390}, {"user_id": 1930, "stars": [], "topic_id": 18681, "date_created": 1302716999.4405029, "message": "(I'll wait for commentary / suggestions on appropriate next steps now...)", "group_id": 1535, "id": 668407}, {"user_id": 1760, "stars": [], "topic_id": 18681, "date_created": 1302780071.564831, "message": "The hook loader in virtualenvwrapper only runs under python 2. That doesn't mean you can't use it with python 3, since it doesn't use the version of python inside the virtualenvs you are creating. Set VIRTUALENVWRAPPER_VIRTUALENV to point to the version of virtualenv you want to run, and set VIRTUALENVWRAPPER_PYTHON to point to a version of python 2.", "group_id": 1535, "id": 682797}]